FROM ruby:3.0.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        libsqlite3-dev \
        sqlite3 \
        ruby-execjs \
        vim \
        yarn \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /derailed

# Install gems
ENV BUNDLE_PATH=/bundle/vendor

# Install bundler
RUN gem install bundler:2.2.32
